### ISSUE TITLE
Change to OpenWhisk NPM package, whisk object deprecated

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-package-jira#4]
See both:
https://www.npmjs.com/package/openwhisk
https://medium.com/openwhisk/updates-to-openwhisk-node-js-actions-ed5556cd5ae9#.xtcrclic4

For how to change to the OpenWhisk NPM package and promises instead of using the whisk object.

**Comment by dgrove-oss** [comment]
Closing issue as project is being archived.
